name: Trigger auto deployment for reactbasic9707a68890f5

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/reactbasic9707a68890f5-AutoDeployTrigger-5652dbac-81f8-4ef1-afb8-7e821ec8c4be.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.REACTBASIC9707A68890F5_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.REACTBASIC9707A68890F5_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.REACTBASIC9707A68890F5_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.REACTBASIC9707A68890F5_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.REACTBASIC9707A68890F5_REGISTRY_PASSWORD }}
          containerAppName: reactbasic9707a68890f5
          resourceGroup: reactbasic9707a688
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


